# David Lawrence Miller 2018

# load the data to use, generated by sp_names.R
load("sp_names.RData")

generate_names <- function(sp_name_dat, probs, type="marine"){

  probs <- probs[[type]][2:length(sp_name_dat[[type]])]
  len <- sample(2:length(sp_name_dat[[type]]), 1, prob=probs)

  sp_dat <- sp_name_dat[[type]][1:len]
  nn <- lapply(sp_dat, function(x) x[,1][sample(1:nrow(x), 1)])
  paste(nn[length(nn):1], col=" ")
}

#print(generate_names(sp_name_dat, probs))



