### post some excellent SDMs to the better microblogging
###  platform botsin dot space

# David Lawrence Miller 2022

# sorry this is here because the script gets run by cron on my vps
setwd("~/sdmbot")


library(ggplot2)
library(mapdata)
library(viridis)
library(rtoot)

# load the data to use, generated by data_setup.R
load("saved.RData")

# load species name generator
source("generate_names.R")

generate_map <- function(spec){
  # extract data from spec
  dat <- spec$dat
  xlim <- spec$extent[1:2]
  ylim <- spec$extent[3:4]
  pos <- spec$pos

  datr <- as.matrix(dat) %*%
            matrix(sample(rep(c(0, 1), c(ncol(dat)-4, 4)), ncol(dat))*
              runif(ncol(dat), -1, 1), ncol=1)
  dat$p <- datr[,1]
  dat$p <- dat$p - mean(dat$p)
  dat$p <- dat$p/max(dat$p)

  dat <- dat[dat$p>0, ]

  p <- ggplot(dat) +
    geom_tile(aes(x=x,y=y, fill=p)) +
    scale_fill_viridis() +
    theme_void() +
    coord_equal(xlim=xlim, ylim=ylim)

  # fill-in the land if we have a marine map
  if(spec$type=="marine"){
    p <- p + borders("world", colour="grey80", fill="grey80")
  }else{
    # else just draw the boundary
    p <- p + borders("world", colour="black", size=0.25)
  }

  # make a name
  aname <- generate_names(sp_name_dat, probs, type=spec$type)

  # where should the species names go?
  if(pos=="topleft"){
    p <- p + annotate("text", x=xlim[1], y=ylim[2], hjust="left",
                      label=aname)
  }else if(pos=="topright"){
    p <- p + annotate("text", x=xlim[2], y=ylim[2], hjust="right",
                      label=aname)
  }else{
    # put it in the bottom left
    p <- p + annotate("text", x=xlim[1], y=ylim[1], hjust="left",
                      label=aname)
  }

  fn <- paste0("posts/sdm_", format(Sys.time(), "%d%b%Y-%H%M"), ".png")
  ggsave(p, file=fn, width=7, height=3, bg="white")
  return(list(fn=fn,
              spp=aname))
}


# generate a map and return the filename
gm <- generate_map(spec[[sample(1:length(spec), 1)]])

# post the file to botsin.space
post_toot(status = gm$spp, media=gm$fn,
          alt_text = paste("a fiction species distribution map for", gm$spp))



