### post some excellent SDMs to the popular microblogging
###  platform twitter dot com

# David Lawrence Miller 2018

setwd("~/sdmbot")
library(ggplot2)
library(mapdata)
library(viridis)

# load the data to use, generated by data_setup.R and sp_names.R
load("saved.RData")
load("sp_names.RData")

generate_map <- function(spec){
  # extract data from spec
  dat <- spec$dat
  xlim <- spec$extent[1:2]
  ylim <- spec$extent[3:4]
  pos <- spec$pos
  starts <- sp_name_dat[[spec$type]]$starts
  ends <- sp_name_dat[[spec$type]]$ends

  datr <- as.matrix(dat) %*%
            matrix(sample(rep(c(0, 1), c(ncol(dat)-4, 4)), ncol(dat))*
              runif(ncol(dat), -1, 1), ncol=1)
  dat$p <- datr[,1]
  dat$p <- dat$p - mean(dat$p)
  dat$p <- dat$p/max(dat$p)

  #dat$p <- dat$p*sample(c(-1,1), 1)

  dat <- dat[dat$p>0, ]

  p <- ggplot(dat) +
    geom_tile(aes(x=x,y=y, fill=p)) +
    scale_fill_viridis() +
    theme_void() +
    coord_equal(xlim=xlim, ylim=ylim)

  # fill-in the land if we have a marine map
  if(spec$type=="marine"){
    p <- p + borders("world", colour="grey80", fill="grey80")
  }else{
    # else just draw the boundary
    p <- p + borders("world", colour="black", size=0.25)
  }

  # where should the species names go?
  if(pos=="topleft"){
    p <- p + annotate("text", x=xlim[1], y=ylim[2], hjust="left",
                      label=paste(sample(starts, 1), sample(ends, 1)))
  }else{
    # put it in the bottom left
    p <- p + annotate("text", x=xlim[1], y=ylim[1], hjust="left",
                      label=paste(sample(starts, 1), sample(ends, 1)))
  }

  fn <- paste0("posts/sdm_", format(Sys.time(), "%d%b%Y-%H%M"), ".png")
  ggsave(p, file=fn, width=7, height=3)
  return(fn)
}

post_it <- function(fn){
  # how to from here:
  # https://github.com/twitter/twurl/issues/58
  fuzzy_dog <- system2("/usr/local/bin/twurl",
                  paste0("-H upload.twitter.com \"/1.1/media/upload.json\" -f ",
                         fn,
                         " -F media -X POST"), stdout=TRUE)

  fuzzy_dog <- sub(".*\"media_id\":(\\d+).*", "\\1", fuzzy_dog)
  cat(fuzzy_dog,"\n")
  fuzzy_dog2 <- system2("/usr/local/bin/twurl",
                        paste0("\"/1.1/statuses/update.json\" -d \"media_ids=",
                               fuzzy_dog,
                               "&status=\""))
}


#fn <- generate_map(spec[[8]])

# generate a map and return the filename
fn <- generate_map(spec[[sample(1:length(spec), 1)]])

# post the file to twitter dot com
post_it(fn)




